### ISSUE TITLE
Expose Menu / Menu Item API

### ISSUE THREAD

**Issue by spolu** [breach/thrust#157]
This is a must have API and fairly low hanging fruit especially knowing that this has been done in node-webkit and atom-shell.

Atom-shell approach seems to be the best, exposing that API for each window. see:
https://github.com/atom/atom-shell/blob/master/atom/browser/default_app/default_app.js
https://github.com/atom/atom-shell/blob/master/docs/api/menu.md

And the implementation: https://github.com/atom/atom-shell/blob/master/atom/browser/api/atom_api_menu.h

-- Edit miketheprogrammer - Added Todos
TODOS ( Roadmap )
- [x] Create Boilerplate binding
- [x] Create way for ApiBinding to access other binding instances in the handler.
- [ ] Menu Rendering 
  - [ ] Cocoa (60%)
  - [ ] Aura   (0%)
- [ ] Event Handling 
  - Note*: Proper event bubbling seems to elude me(miketheprogrammer). I have had to implement a style of recursive long polling in C++ using PostTask.
  - [x] Cocoa (100%) - Long Polling Version.
  - [ ] Aura (0%)
- [ ] Research Application logic needs. (i.e.) With window dependent menu items does the menu need awareness of the current focused window. i.e. Copy/Paste 
- [ ] Tests

-- Investigate better solution to events. Long Polling causes an extreme amount of CPU Wakeups with iterative loops for (N,M) where N is the number of registered bindings and M is the number of events registered to that binding. The amount of work done on idle wakeups seems negligible however, in order to maintain responsive and reduce jank, the polls have to be very short intervals, highest probably 200 ms, although 40-160ms would be the golden range. Preferably some sort of graceful throttling method would be great.

**Comment by hachi8833** [comment]
+1
