### ISSUE TITLE
Menus broken on Mac OS X 10.10.2

### ISSUE THREAD

**Issue by joshmarinacci** [breach/thrust#246]
Using the simple menu test in node-thrust I am unable to get the system menu to work.  With some debugging I can confirm that the node bindings are sending the menu commands to the native process, but they don't result in an actual menu created.  Also, there is constant debug output whenever you move the mouse.

Mac OSX version:  10.10.2.  (Yosemite)
Node version: v0.10.30  (though, this shouldn't matter).
node-thrust version: 0.7.6-rc.1

**Comment by callodacity** [comment]
Hey @joshmarinacci I'm struggling to find examples/specific documentation on how to use the menu api with thrust.
I'm using node-thrust as well and judging by your comment it seems you had some success!
The [https://github.com/breach/thrust/blob/master/docs/api/menu.md](menu api) is a little obscure to me..

To create a window one calls `var window = api.window(options)`. I'm attempting to create menu items with no success by calling things similar to `var menu = api.menu(); menu.add_item('item', 'item');`. 

I feel like I'm shooting in the dark here. Any chance you could put me in the right direction?
