### ISSUE TITLE
How do I communicate from thrust back to the main rantime? 

### ISSUE THREAD

**Issue by debunge** [breach/thrust#259]
I've checked the docs, honestly, but how do I, for example, call function from my main.go on jquery click event? I mean I can run http server from go and send get/post from html to localhost, but this is kind of defies the whole idea. I can use any browser with standart go http server.

**Comment by miketheprogrammer** [comment]
You should have posted this in the go-thrust thread.

Please look at https://github.com/miketheprogrammer/go-thrust/blob/master/tutorials/basic_remote_messaging/basic_remote_messaging.go

And no, RESTfull connections will always be the easiest way to create portable applications.
Remote, is only part of thrust, so your application will not be portable to standard web.

Basically to do remote method invocation.

In thrust create a remote handlers, then check the EventResult for what was send, and then handle it.

Remote is just a messaging framework, you would need to write your own RPC layer on top of it.

**Comment by debunge** [comment]
I see. Thank you.
