### ISSUE TITLE
On Windows, taskbar rightclick menu is not appearing.

### ISSUE THREAD

**Issue by LaylConway** [breach/thrust#263]
When on Windows, right-clicking on a window in the task bar will not open a right-click menu to allow for example closing it. This might be a Windows 8/8.1 issue only, I have not checked on earlier versions of Windows.

**Comment by miketheprogrammer** [comment]
I wanted to comment on your other thread earlier but am extremely busy. In
response to this however. There is an api call for context menu. Use that
call

**Comment by LaylConway** [comment]
Ah thanks, it seems I've misread the menu docs.

**Comment by miketheprogrammer** [comment]
The difficulty is getting the front-end to trigger the backend. When a user
right clicks. It's a he'll of a lot of code just for a right click
