### ISSUE TITLE
nodejs example not working?

### ISSUE THREAD

**Issue by drmonty** [breach/thrust#267]
**OS**: Ubuntu 14.10 x86_64
**nodejs**: nodejs 0.12.0 or iojs 1.3.0
**node-thrust**: v0.7.6-rc.1

The example in [README.md](https://github.com/breach/thrust/blob/master/README.md) for nodejs

```
require('node-thrust')(function(err, api) { 
  api.window({ root_url: 'https://breach.cc' }).show();
});
```

starts thrust, but won't display the requested url (just a blank site).
Also adding some flags (for example `set_kiosk`) to window won't get executed:

```
require('node-thrust')(function(err, api) { 
  api.window({ root_url: 'https://breach.cc', set_kiosk: true }).show();
});
```

Am I missing something? Thanks :)

**Comment by hoytech** [comment]
breach.cc doesn't seem to be listening on the https port (it hangs in a normal browser too). Try a different URL.

**Comment by drmonty** [comment]
Thanks @hoytech using a different url works :).
`set_kiosk` still won't get executed.

**Comment by hoytech** [comment]
Some things like dev tools and kiosk mode will only work after the window has already been shown so you need to do it in this order:

    require('node-thrust')(function(err, api) {
      var w = api.window({ root_url: 'http://google.ca' });
      w.show();
      w.set_kiosk(true);
    });

**Comment by drmonty** [comment]
Thanks so much :) - works.
